spring:
  application:
    name: demo
  datasource:
    driverClassName: com.mysql.jdbc.Driver
      #--------------------------
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
    initialSize: '50'
    minIdle: '5'
    maxActive: '1000'
        # 配置获取连接等待超时的时间
    maxWait: '3000'
    removeAbandoned: 'true'
    removeAbandonedTimeout: '180'
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: '60000'
        # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: '300000'
    validationQuery: select version()
    testWhileIdle: 'true'
    testOnBorrow: 'false'
    testOnReturn: 'false'
        # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: 'true'
    maxPoolPreparedStatementPerConnectionSize: '100'
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: 'stat,log4j'
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: 'druid.stat.mergeSql: true, druid.stat.slowSqlMillis: 5000'
        # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: 'true'
  datasourceread:
    url: jdbc:mysql://123.206.85.162:3306/test_mysql
    username: media7312
    password: 731296997
  datasourcewrite:
    url: jdbc:mysql://123.206.85.162:3306/test_shop
    username: media7312
    password: 731296997

mybatis:
  mapper-locations: classpath:mapper/*.xml